apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-custom
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      schedulerName: my-scheduler
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80